name: Lint and Test Code

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pytest

    - name: Run pylint
      run: |
        pylint **/*.py

    - name: Run unit tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest